# Generated by Django 5.0.6 on 2024-07-17 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='AboutUS/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('title', models.CharField(blank=True, default='Hat', max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Announcements/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Announcements/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('title', models.CharField(blank=True, default='Company Name', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='CompaniesLogo/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('title2', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, max_length=300, null=True)),
                ('month', models.CharField(blank=True, max_length=300, null=True)),
                ('year', models.CharField(blank=True, max_length=300, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('physicalAdress', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True)),
                ('twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('email1', models.CharField(blank=True, max_length=300, null=True)),
                ('email2', models.CharField(blank=True, max_length=300, null=True)),
                ('email3', models.CharField(blank=True, max_length=300, null=True)),
                ('phoneNumber1', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('phoneNumber2', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('phoneNumber3', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('phoneNumber4', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('title', models.CharField(blank=True, default='Hat image', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='heroSection/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy1', models.CharField(blank=True, max_length=300, null=True)),
                ('policy2', models.CharField(blank=True, max_length=300, null=True)),
                ('policy3', models.CharField(blank=True, max_length=300, null=True)),
                ('policy4', models.CharField(blank=True, max_length=300, null=True)),
                ('policy5', models.CharField(blank=True, max_length=300, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='PresidentSpeech',
            fields=[
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='presidentSection/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='presidentSection/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('title', models.CharField(blank=True, default='Hat', max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, default='Hat', max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Resources/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Resources/')),
                ('video_url', models.CharField(blank=True, default='Hat', max_length=300, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Staffs/')),
                ('position', models.CharField(blank=True, max_length=300, null=True)),
                ('contact1', models.CharField(blank=True, max_length=300, null=True)),
                ('contact2', models.CharField(blank=True, max_length=300, null=True)),
                ('contact3', models.CharField(blank=True, max_length=300, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsofService',
            fields=[
                ('term1', models.CharField(blank=True, max_length=300, null=True)),
                ('term2', models.CharField(blank=True, max_length=300, null=True)),
                ('term3', models.CharField(blank=True, max_length=300, null=True)),
                ('term4', models.CharField(blank=True, max_length=300, null=True)),
                ('term5', models.CharField(blank=True, max_length=300, null=True)),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('title', models.CharField(blank=True, default='Footer', max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logo/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.contacts')),
                ('policies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.policies')),
                ('termsofService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.termsofservice')),
            ],
        ),
    ]
