# Generated by Django 5.0.6 on 2024-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='title2',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='month',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='year',
        ),
        migrations.AddField(
            model_name='conference',
            name='date_of_conference',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
