# Generated by Django 5.0.6 on 2024-07-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_title2_conference_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
