# Generated by Django 5.0.6 on 2024-09-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_resource_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='references',
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.CharField(blank=True, max_length=300, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='homepage.resource')),
            ],
        ),
    ]
