# Generated by Django 5.0.6 on 2024-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_resource_references_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='references',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
