# Generated by Django 5.0.6 on 2024-09-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_resource_references_delete_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='references',
        ),
        migrations.AddField(
            model_name='resource',
            name='ref1',
            field=models.CharField(blank=True, default='Hat', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='ref2',
            field=models.CharField(blank=True, default='Hat', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='ref3',
            field=models.CharField(blank=True, default='Hat', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='ref4',
            field=models.CharField(blank=True, default='Hat', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='ref5',
            field=models.CharField(blank=True, default='Hat', max_length=300, null=True),
        ),
    ]
