# Generated by Django 5.0.6 on 2024-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_resource_references_resource_ref1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentspeech',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presidentspeech',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
