# Generated by Django 5.0.6 on 2024-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_presidentspeech_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentspeech',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
