# Generated by Django 5.0.6 on 2024-10-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_presidentspeech_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidentspeech',
            name='cheo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
