# Generated by Django 5.0.6 on 2024-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_presidentspeech_cheo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, help_text='Upload the research paper in PDF format.', null=True, upload_to='research_papers/'),
        ),
    ]
