# Generated by Django 5.0.6 on 2024-10-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_resource_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='document',
            field=models.FileField(blank=True, help_text='Upload the research paper in PDF format.', null=True, upload_to='Announce_Docs/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
