# Generated by Django 5.0.6 on 2024-10-16 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_announce_document_alter_resource_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, help_text='Upload the research paper in PDF format.', null=True, upload_to='Resouces_Docs/')),
                ('dateIssued', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-dateIssued'],
            },
        ),
    ]
